### ISSUE TITLE
spearfishing misses fish in the bottom row

### ISSUE THREAD

**Issue by AAfetisov** [InitialDet/AutoHook#115]
size: large
speed: slow
misses bottom row fish all the time

https://github.com/InitialDet/AutoHook/assets/1430709/2e385f6a-b225-4c5d-bd76-db19dcd37c31

**Comment by InitialDet** [comment]
Some types of fish requires you to adjust the size of the gig hitbox in the plugin options.
AutoGig is a very experimental feature so thats the only solution for now.
