### ISSUE TITLE
Update 3.0.0 Issues localization

### ISSUE THREAD

**Issue by cptjabberwock** [InitialDet/AutoHook#119]
Game fully in english but options shown in french 

![image](https://github.com/InitialDet/AutoHook/assets/35723546/099f64a5-d6a5-4296-91bf-666ada71fdff)

**Comment by InitialDet** [comment]
hmm yeah the localization for autocasts are not being updated correctly, i'll look into it

**Comment by InitialDet** [comment]
Should be fixed on 3.0.0.3, feel free to reopen if you notice anything else
