### ISSUE TITLE
Opening AutoHook config window changes ItemSpacing style globally

### ISSUE THREAD

**Issue by tjrawrin** [InitialDet/AutoHook#12]
Hi! Opening the config window for AutoHook sets the `ItemSpacing` style for all Dalamud plugin windows to a value of `10` horizontally and `8` vertically. This overrides what a user has set for their theme, weather it be the default Dalamud Standard or Dalamud Classic theme or a custom theme. 

Below is the line of code that adjusts this style setting. Would it be possible to remove this style setting from AutoHook or reset the values back to the original of the current theme after the config window is closed?

https://github.com/InitialDet/AutoHook/blob/e0479fa18658e57c22cb5245dd57505ed1805d7d/AutoHook/PluginUI.cs#L59

Thanks!

**Comment by InitialDet** [comment]
Pushed a new version removing this line, lemme know if it resolved the issue

**Comment by tjrawrin** [comment]
Looks good! The spacing in other windows aren't affected anymore when the AutoHook config window is opened. Thanks for the quick update. 🤗
