### ISSUE TITLE
Bait option: auto switch to if you do or do not have intuition

### ISSUE THREAD

**Issue by Jaksuhn** [InitialDet/AutoHook#121]
New rework allows for a huge amount of fish to become a preset, however while it's now capable of doing the setup for many fish, it can't do it again after the intuition drops.

Case in point: mayaman

catch caiman 5 times, switch to mayfly bait. Works just fine. When the intuition drops though, you need to go back to sky spoon lures to recatch the caimans, but there's no way of doing that currently

**Comment by InitialDet** [comment]
I'll try to add an option to swap bait/preset when you gain/lose intuition. this should be enough i think?

**Comment by Jaksuhn** [comment]
That would be perfect.

**Comment by FunkeyMonkey** [comment]
Came here to request just this as i'm working on Feast of Famine, this would be amazing to have put in. Keep up the great work, loving the plugin!

**Comment by InitialDet** [comment]
Ive add an option for this, couldnt test too much but should be all good. Let me know if you notice any weird bug.
