### ISSUE TITLE
Experimental source no working

### ISSUE THREAD

**Issue by ghostesla** [InitialDet/AutoHook#125]
when you add the "https://raw.githubusercontent.com/InitialDet/MyDalamudPlugins/main/pluginmaster.json" and save it will not show up within the plugins.

**Comment by InitialDet** [comment]
Double check if you correctly added the repo link in the dalamud configuration, it should look like this
![image](https://github.com/InitialDet/AutoHook/assets/13919114/bdb3d4f5-f110-413a-9cd5-5d762cfcbc67)

Also remove any "mega repos" you might have installed, it could cause conflicts.

**Comment by mshu1** [comment]
Hi InitialDet. I currently have the same problem trying to install it on the CN server. My CN Dalamud ver is vD7.11.0.0. I double checked the link and is quite certain what I put is correct and does not have issues installing any plugins that are readily available on Dalamud.

Thanks again for this amazing plugin.
