### ISSUE TITLE
Double/Triple Hook

### ISSUE THREAD

**Issue by Driguer1** [InitialDet/AutoHook#126]
You can't set triple or double hook unless is with a mooch with this new rework. If you are trying to catch only a specific fish you can only set identical cast or surface slap, but you cant set to double/triple hook after

**Comment by InitialDet** [comment]
i didnt quite understand, could you be more specific? Is the double/triple hook option not working or something?

**Comment by Driguer1** [comment]
For a example if i want to catch only jellyfish. I can make a jellyfish preset in the custom menu, set to if i catch a jellyfish i will use "Identical Cast".. But i cannot chain it with a Double/Triple Hook. What is missing is the option to be able to use identical cast and double hook in a chain for a specific fish. The only option for double/triple hook is in the mooch tab which doesnt work for specific non-mooch fish :c

**Comment by InitialDet** [comment]
You can do that, on the bait preset you can set to use Double/Triple Hook if you have identical cast active. So you can catch a jellyfish, use identical cast, and the next hook is goin to be Double or Triple
![image](https://github.com/InitialDet/AutoHook/assets/13919114/e9d94aac-6819-42c3-b6e9-3c62bb228d60)

**Comment by InitialDet** [comment]
Heres an example, recorded with double audio by mistake but thats fine.

https://github.com/InitialDet/AutoHook/assets/13919114/92d53f74-35a9-47e8-89ca-802585f768ca

**Comment by Driguer1** [comment]
ohh, i didnt see you could set on the bait tab x.x .. well that solve the problem, thank you so much for your help/quick response and your plugin.
