### ISSUE TITLE
Suggestion: Option to Prioritize Mooch over Patience

### ISSUE THREAD

**Issue by VelvetScar** [InitialDet/AutoHook#128]
When I have the opportunity to mooch right as Patience has times out (when both "Auto Mooch" and "Patience" are selected under "Auto Casts"), it will use Patience instead of Mooch II, wasting the potential Mooch opportunity (this occurs with and without "Don't Cancel Mooch" enabled).

My suggestion is to have an option to prioritize Mooch/Mooch II rather than refreshing Patience and cancelling the mooch, since many fish don't need the Patience buff at all once a Mooch goes through. (Also thanks for working on this plugin, it's absolutely fantastic :D )

**Comment by InitialDet** [comment]
It'll only cancel mooch if "Don't cancel mooch" is disabled, otherwise mooch always has priority, also theres a new option to refresh patience before it expires so that could be helpful.
