### ISSUE TITLE
Suggestion: Add a short randomized delay between a fish biting and hooking

### ISSUE THREAD

**Issue by mwcarew** [InitialDet/AutoHook#130]
https://github.com/InitialDet/AutoHook/issues/109

Referencing the old issue here.

Would love a feature that adds a short randomized delay between a fish biting and hooking the fish. Right now, AutoHook instantly hooks things and it looks unnatural if fishing around other people. When someone is using AutoHook, I can never tell what sort of bite they got before they're already reeling it in and it's very obvious they're using this plugin or something similar.

With the old version of AutoHook, I added the following to line 140 in HookManager.cs:

```
        Random rnd = new Random();
        int delay = rnd.Next(301,843);

        await Task.Delay(delay);
```

**Comment by InitialDet** [comment]
i'll add be adding a delay for hooking in the next release

**Comment by mwcarew** [comment]
@InitialDet That's wonderful. Thank you for all your hard work!
