### ISSUE TITLE
Prize Catch option "only use when Mooch II is not available" is not working correctly

### ISSUE THREAD

**Issue by Jagerka** [InitialDet/AutoHook#136]
PC option selected to only use when Mooch II is on cooldown - yet PC is picked first even when Mooch II is available.

Settings under Auto Casts:
Auto Mooch - selected
Use Mooch II - selected (condition: above 100 GP)
Use only when Fisher's Intiution is active - not selected

Prize Catch - selected (condition: above 200 GP)
Only use when Mooch II is NOT available - READ >>>  - selected
Only use when Identical Cast is Active - not selected

**Comment by InitialDet** [comment]
Should be fixed now
