### ISSUE TITLE
How do you reset the Caught: X amount?

### ISSUE THREAD

**Issue by FFXIVWytes** [InitialDet/AutoHook#137]
![image](https://github.com/InitialDet/AutoHook/assets/80117346/421e14cc-dc67-48ba-a6e2-31de0488c096)

1) How can I reset these to 0?

2) This counter only goes up +1 even if you use double hook. Is it possible to have it reflect the number of fish caught?

**Comment by InitialDet** [comment]
Sorry for the delay, currently you can reset the counter by quiting fishing (putting the rod away).

Ill fixing the correct amount when using double/triple hook
