### ISSUE TITLE
Suggestion: Double/Triple Hook Time Thresholds

### ISSUE THREAD

**Issue by Ocean1148** [InitialDet/AutoHook#145]
Suggestion: Double/Triple Hook Time Thresholds 
for example:
Double hook if !! at 8-16sec threshold
Triple Hook if ! at >=20sec
(ignoring all your other presets; double/triple hook settings having their own category under bait/mooch.)

**Comment by GoblinGuide** [comment]
Especially with Ocean Fishing giving mogtomes now, this would be very nice. Make life a lot easier.

(ideally it could handle multiple ranges - DH !! at 2-3 or 6+ - but even just one range per hook/per bite would be a really big help!)
