### ISSUE TITLE
Feature Request for Identical Cast

### ISSUE THREAD

**Issue by KHShadowrunner** [InitialDet/AutoHook#17]
Any way you would consider using the logic from mooch/double/triplehook to use identical cast?

The optimal setup would be to be able to Identical Cast/Favor/TripleHook, but that might be asking a lot and a simple spender would be hopefully more easy to implement.

**Comment by KHShadowrunner** [comment]
I guess not the double/triple logic but mooch - specifying fish to use IC on.

**Comment by InitialDet** [comment]
I went with the simple way and added Surface Slap/Identical Cast for specifying fish in the Bait/Mooch tab. 

The "Identical Cast/Favor/TripleHook" combo might get a bit complicated with so many auto casts options
