### ISSUE TITLE
Prevent AFK status while autocast

### ISSUE THREAD

**Issue by DenL** [InitialDet/AutoHook#19]
If you leave autocast on and don't touch your keyboard (or alt tabbed out), your character would eventually go into afk status, but autocast still continues. It would seem a very obvious 3rd party tool usage and might get you reported.

**Comment by QuackProfit** [comment]
Set your AFK timer to "never".

**Comment by DenL** [comment]
I'm aware of both of the above solutions but i'd still like to appear AFK when I'm actually afk. Just thought having it automatic works better than manually switching afk timers/modes.

**Comment by InitialDet** [comment]
So, ive added an experimental anti-afk status that I saw on the XIVDeck plugin. I didn test it tho, so I hope it works xD

**Comment by InitialDet** [comment]
Well, I did some tests using /afk and it seems to work fine. Feel free to reopen this issue if it doesn't work for you.
