### ISSUE TITLE
Only hook on specific tug

### ISSUE THREAD

**Issue by MarkusWo** [InitialDet/AutoHook#2]
Hey, I love this addon. I know you said to expect bugs. But I have yet to encounter one. Do you mind suggestions for the addon? At the moment I am trying to catch some rare fish that have a heavy tug, i.e. fish that show !!! above your head when they bite. Currently, your addon is a hooking all fish, but could it be added that it only autohooks fish when you get the !!! heavy tug and just ignore the other fish, i.e. when you get ! or !!? I usually don't want to bother with other fish, if I know the one I am looking for is not the one biting. 

Conversely, sometimes I might be looking only for fish with the light tug (!) maybe for mooching. If you cannot see the tug of the fish that's biting, another way to help here would be if I could specify a maximum and minimum time in which the plugin should autohook everything. For example, if I know (from the fishing wikis) that the fish I am looking for only bites after 20 seconds, I might want autohook to ignore all fish that bite before 20 seconds. Just some thoughts I had how you could maybe have the plugin customizable. Thank You again for this plugin!

**Comment by InitialDet** [comment]
Thank you for the feedback and great suggestions. I'll take sometime and see what i can do about these QoL changes, i can't promise it'll be quick but I'll try.

**Comment by InitialDet** [comment]
It took me some time but I think I managed to make something cool. The new version should be up soon. If yall find any errors please open a new issue so I can check and fix it.
