### ISSUE TITLE
Feature Idea - Chum per-bait

### ISSUE THREAD

**Issue by panzerchris** [InitialDet/AutoHook#20]
I was thinking there's a use case for chum-per-bait. If you're aiming for fish like Diamond-eye, you often want to use chum for the first catch and then mooch the Rock Saltfish. There's a few other examples along these lines. Would it be possible to set chum on the bait options, so that we can make it use chum for the first cast but then mooch after that?

**Comment by DenL** [comment]
Alternatively have the plugin disable Chum while mooching. Currently if you have chum enabled, it would chum and lose the moochi opportunity even when the fish is set up to mooch.

**Comment by InitialDet** [comment]
Yeah i'll try to fix this.

**Comment by InitialDet** [comment]
I've added an option to not use actions that cancel mooch. This should resolve your problem.

Feel free to reopen this issue if that wasn't quite what you suggested

**Comment by DenL** [comment]
Is it possible to only not Chum (+ etc.) when plugin is actually set to mooch?
e.g. You hook a copperfish that can be mooched, but based on your bait settings, it would not mooch and cast with base bait again. In this case, Chum could still be used.
e,g, You hook a silverfish that can be mooched, and will be mooched based on bait settings. In this case plugin would not Chum.

**Comment by InitialDet** [comment]
That is true, didnt think of that. I'll fix it

**Comment by InitialDet** [comment]
Just pushed a new version, it should be fine now
