### ISSUE TITLE
"Stop Fishing After..." doesn't seem to work

### ISSUE THREAD

**Issue by DenL** [InitialDet/AutoHook#21]
Have not test this feature with bait yet, but with fish, having "Stop fishing after..." set to 1, it would still continue autocasting even after fish has been caught.

**Comment by InitialDet** [comment]
Hmm im goin to double check it, could you tell me wich fish did you use try to catch?

**Comment by DenL** [comment]
I tried with several big fishes. I also just tried with a regular fish (Kissing Trout) and it also didn't work.

**Comment by InitialDet** [comment]
Aight this should be fixed now
