### ISSUE TITLE
Feature Request: "Use Identical Cast" doesn't look like it's working when caught Collectables

### ISSUE THREAD

**Issue by owatan** [InitialDet/AutoHook#22]
Added by #17 "Use Identical Cast" option does not look like it's working when caught Collectables.

I think changing this will work but I have no idea to change.
https://github.com/InitialDet/AutoHook/blob/main/AutoHook/Configurations/AutoCastsConfig.cs#L228

Do you plan to support it ?

**Comment by InitialDet** [comment]
Thats weird, I'll take a look at it.

**Comment by InitialDet** [comment]
Sorry for the delay, it should be fine now

**Comment by owatan** [comment]
Seems to be working fine, thanks <3
