### ISSUE TITLE
Plugins doesn't autohook after fish gets away.

### ISSUE THREAD

**Issue by miaki3457** [InitialDet/AutoHook#23]
Autohook a kink among (!!!) and the fish gets away.

after that ,  plugins doesn't autohook But still will auto cast line after lose bait.

**Comment by InitialDet** [comment]
Did you check your configurations? make sure you have "Hook Legendary (!!!)" enabled in the general tab or in the bait/mooch tab

**Comment by InitialDet** [comment]
I tried to reproduce but it always try to autohook after a fish gets away.

Try to type /xllog in the chat and check in the log window check if a message like this appears after a fish bite 
![image](https://user-images.githubusercontent.com/13919114/182162915-520ff900-2e07-4a60-8d1d-68b9eb3ebc22.png)

**Comment by miaki3457** [comment]
i found the problem.
that's no problem in English client or orther language.
when i use modify client (chinese) it's happens

**Comment by InitialDet** [comment]
Oh i see, i'll see if i can add support for Chinese. Thanks for reporting

**Comment by miaki3457** [comment]
Thanks, I replace four Chinese regexes with Japanese now.

**Comment by InitialDet** [comment]
Tell me if the new version works for you

**Comment by InitialDet** [comment]
It should be working in the newest version, feel free to reopen this issue if you find any problems
