### ISSUE TITLE
Bug: Fish still hooked even if "Hook Weak"/"Hook Strong" is unchecked in bait settings

### ISSUE THREAD

**Issue by DenL** [InitialDet/AutoHook#28]
I set up a couple baits to only hook legendary bite. However all bites are still hooked as if the bait setting is ignored.
Baits I tried: Giant Crane Fly, Sky Faerie, Granite Crab

This feature was working before in a previous release so it's a new issue.

**Comment by InitialDet** [comment]
What's your current version? Im trying to reproduce it here but its working fine

**Comment by InitialDet** [comment]
Actually, try the new 2.2.3.1 version

**Comment by DenL** [comment]
2.2.3.0

Do I have to stop fishing and restart for the settings to apply?
Not sure if this matters but I also have Global Auto Mooch on in Auto Cast settings. This is the only difference i can think of settings wise (vs before when it was working)

**Comment by InitialDet** [comment]
I've added a line by mistake that was preventing the plugin from swapping between bait configs, it should be fine now

**Comment by DenL** [comment]
Thanks, will try once addon updates.
