### ISSUE TITLE
Suggestions: Cordial usage GP threshold

### ISSUE THREAD

**Issue by DenL** [InitialDet/AutoHook#30]
Hi, want to thank you for this addon again and being so responsive to tickets.

Currently, cordials would be used as long as the immediate usage does not result in overcap. However during fish, with thaliak's favor and patient generating stacks readily, using cordial immediately below threshold (e.g. right after patience II use) would almost always result in overcap in subsequent auto-regen of GP.

Would be great if there could be an option to only use cordials when below a certain amount of GP. "Use when GP below X" or "Use when GP is X below max" both works.

Thanks!

**Comment by InitialDet** [comment]
Sorry for the delay, I've added this on the latest version
