### ISSUE TITLE
Suggestion: Auto accept collectability 

### ISSUE THREAD

**Issue by Rosabeth** [InitialDet/AutoHook#31]
As title said, do you think if that's possible? 
Thank you for this amazing plugin

**Comment by InitialDet** [comment]
There's a fantastic plugin that does that already 
https://github.com/daemitus/YesAlready

I was confused about your suggestion because I use this plugin and never saw the collectability dialog

**Comment by Rosabeth** [comment]
Ah, I didn't have that plugin is why, thank you!
