### ISSUE TITLE
Using Identical Cast based on prior fish opposed to bait/mooch

### ISSUE THREAD

**Issue by KHShadowrunner** [InitialDet/AutoHook#32]
I know I had suggested something similar before, but I think it got either lost or it's not possible - so i figured I'd check again.

Would it be possible to detect what fish was previously caught in order to determine if you want to use Identical Cast? Currently it will only use it based on Bait/Mooch, which would fire on every fish in the pool rather than the one you're targeting.

It might not be possible, if not would it be possible to add a global delay akin to the min/max wait to use hook? A delay to use cast? Would allow you to use skills during the small window you set to target particulars.

**Comment by InitialDet** [comment]
If you add the fish to the bait/mooch tab and check the option, Identical Cast will be used next time that fish is hooked.

**Comment by InitialDet** [comment]
Or is that not quite exactly what ur suggesting?

**Comment by KHShadowrunner** [comment]
Might need to report it as not working then, as it sounds like what I tried to do.

Tried to set up for Thavnairian calamari - set it up as that name and enabled identical cast but it would not fire. If I manually enabled Identical Case, Double Hook/Triple Hook also would not trigger.

**Comment by KHShadowrunner** [comment]
Yeah just to test, went to Lavender Beds and used a versatile lure. 

First created a new bait/mooch and renamed it to pipira, only changing the 'Identical Cast' option to true. On next hook - no change.
Then clicked to add current Bait to add Versatile Lure, only changing the same Identical Cast option, and it worked as expected.

Hmmm.. this gets more interesting. Manually adding Versatile Lure, Auto Mooch does not work, but enabling surface slap does work. If I disable that and instead enable to use double/triple hook only if Identical cast is enabled, mooch now works. 
Not sure if manually adding fish is working. Disabling specifically the double/triple hook but leaving the other option check makes mooch fail.

Seems like there's a weird check being missed maybe?

**Comment by InitialDet** [comment]
Yeah for now to avoid conflict with different languages, everything should be typed exactly like in-game.

I'm assuming It worked when you fixed the capitalizations?

**Comment by KHShadowrunner** [comment]
Correct, looks like it works. The capitalization is a bit of a challenge as the item name uses different capitals than the actual hook name, but it's an easy catch so. All good here!
