### ISSUE TITLE
DH/TH Suggestions

### ISSUE THREAD

**Issue by Valmere** [InitialDet/AutoHook#36]
Would it be possible to expand the current hook settings to use DH/TH on legendary hooks? For ocean fishing purposes since Patience isn't used it would be nice to have a setting to auto triple hook any !!! tugs.

Edit: Would be useful in Diadem too for mooched !!! tugs during weather windows.

It would also be nice to have an option to use whichever hook is currently available GP-wise instead of solely one or the other.

**Comment by InitialDet** [comment]
I've added this option on the latest version
