### ISSUE TITLE
Suggestion: Enabling both Double and Triple Hook

### ISSUE THREAD

**Issue by Izanami-no-mikoto** [InitialDet/AutoHook#39]
It would be amazing if you could turn on the "Use Double Hook" and the "Use Triple Hook" options both at once. So that if the hook triggers it would use either Hook, Double Hook, or Tripple Hook depending on how much GP you have.

**Comment by InitialDet** [comment]
There's not much use enabling both option, for example, if you enable both options with max GP, the first hook is going to be a triple hook and every other hook will always be a double hook because it'll never reach the GP for the next triple hook
