### ISSUE TITLE
Suggestion: Profiles

### ISSUE THREAD

**Issue by fcukdat** [InitialDet/AutoHook#40]
A **profile** feature would be nice where different scenarios, can have different bait/mooch configurations.

ez example:
**Ocean fishing**:
Different objectives but potentially using same bait. Basically being able to save/switch these "profiles" or configurations of the bait/mooch settings would be nice. 
Also means can just configure different "profiles" for each route/map/weathercondition/etc, makes for a quick and dirty way of getting around having those variables available in the settings.

I imagine the profiles would be something along the lines of a collection of the existing `Current bait/mooch:` configurations **name, description** and *potential ability to export/import if cbb*.

**Comment by InitialDet** [comment]
That's a good idea, I'll see what I can do after 2.3.0.0

**Comment by InitialDet** [comment]
Sorry for the delay, ive added a preset option in the newest version.
