### ISSUE TITLE
Bug: Plugin constantly tries to use cordial even when still on cooldown

### ISSUE THREAD

**Issue by Izanami-no-mikoto** [InitialDet/AutoHook#41]
When using the plugin and enabling the "Use Cordials" function it will use the cordials when up but also when they are still on cooldown. It will keep pressing the cordial and the game will display the "Not ready yet" error until you turn off the "Use Cordials" function.

**Comment by InitialDet** [comment]
Yeah thanks for spotting that, I forgor to check the pot cooldown. It should be fine now
