### ISSUE TITLE
Suggestion: Wariness Threshold for Nature's Bounty (AutoGig)

### ISSUE THREAD

**Issue by royblazer** [InitialDet/AutoHook#43]
For the "Use Nature's Bounty" when doing AutoGig: to include an optional threshold to stop using it after a certain % of the wariness bar is filled, like 50%, 75% full, etc. Sometimes a fish will come late enough to use up the buff, but not leave enough time to have another reasonable use.

**Comment by InitialDet** [comment]
ill try and and see what i can do about that, AutoGig is a very experimental feature and tbh im surprised the option works at all LOL

**Comment by InitialDet** [comment]
Nature's Bounty will now only be used when the target fish is detected on the screen, its not a perfect solution but it works most of the time.
