### ISSUE TITLE
Suggestion for spearfishing

### ISSUE THREAD

**Issue by sylvester1542** [InitialDet/AutoHook#44]
Please consider adding an option to use Nature's Bounty only if the targeted fish appear on the fishing window, currently it waste a lot of GP. 

Thank you for the great plugin.

**Comment by xPumaa** [comment]
this won't work with fast fishes

**Comment by keoShine** [comment]
Tangential suggestion: an option to only cast Nature's Bounty if <X seconds are left on the spearfishing attempt to prevent dumping 100GP needlessly if it's unlikely (to the user's assessment of likelihood) another of the target fish will even have a chance to spawn before the attempt is over..

**Comment by xPumaa** [comment]
> Tangential suggestion: an option to skip auto-casting Nature's Bounty if <X seconds are left on the spearfishing attempt to prevent dumping 100GP needlessly if it's unlikely (to the user's assessment of likelihood) another of the target fish will even have a chance to spawn before the attempt is over..

#43

**Comment by InitialDet** [comment]
Nature's Bounty will now only be used when the target fish is detected on the screen, its not a perfect solution but it works most of the time.
