### ISSUE TITLE
[Suggestion] Remove the "precision/powerful" hookset options from  weak (!) and strong (!!) bites.

### ISSUE THREAD

**Issue by cc12138030** [InitialDet/AutoHook#46]
This is just a suggestion to reduce UI clutter. Weak bites (!) are _always_ precision, and strong bites (!!) are _always_ powerful. The only one that is split depending on fish is the ferocious/legendary bite (!!!). 

Having the option there doesn't really hurt anything, this is really just a cosmetic suggestion. Feel free to ignore or whatever, just thought I'd throw it out there.

**Comment by InitialDet** [comment]
I appreciate the feedback. The selectable hookset was a very requested feature, but I didn't know if it only applied to !!! bites so I just added it to all options to be extra safe. I'll leave it for now but if I ever touch the UI again I'll probably see if its fine to remove them.
