### ISSUE TITLE
[Bug] Hook Legendary (!!!) toggle for Default Mooch always uses Powerful Hookset

### ISSUE THREAD

**Issue by Lexentale** [InitialDet/AutoHook#47]
I've observed this behavior a number of times, but it's naturally difficult to replicate. Regardless of what option is chosen for `Hook Legendary (!!!)` on the **Default Mooch** tab listed under **General**, AutoHook appears to always use Powerful Hookset when under Patience I/II.

![84753945734](https://user-images.githubusercontent.com/107435698/194093677-2217a076-e6eb-41f6-8d8f-a345e9a33cd3.jpg)

I made sure no other sub-options or pre-defined bait configurations were interfering. This was very noticeable on legendary fish with weak bites that required a mooch, where I observed a very skewed amount of misses. The character animation also clearly shows it attempted using powerful (both hands pulling the rod), not precision.

**Comment by InitialDet** [comment]
Hmm im trying to replicate it here but nothing seems wrong, does this only happen for you when mooching?

**Comment by InitialDet** [comment]
I didn't manage to replicate but I pushed some small changes and see if it works. 
If you ever come across this problem again, type /xllog in the chat and look for the following line:
![image](https://user-images.githubusercontent.com/13919114/194120381-7c9f5d8a-11b7-4477-a7ea-53b18fd1649f.png)

It says if the config used was DefaultCast/DefaultMooch or a Custom one, this way we can check if its using the wrong one or not
