### ISSUE TITLE
Suggestion: Toggle on and off command / release option

### ISSUE THREAD

**Issue by WilliamW1979** [InitialDet/AutoHook#48]
/ahon and /ahoff are great if you want to specifically make sure that you have it on and off, but lets say I want to throw back any fish. I have to make sure it is off, bring up the release list, then turn it on. It would be easier to make a macro to would switch between the two instead of two separate macros.

Also a built in release fish option would make this awesome so that I don't have to manually do it at each hole. The option I would hope to have with it is to keep say rare fish and throw back the ones that are not rare. (Or keep new fish throwing back fish you already gathered in the past).

**Comment by InitialDet** [comment]
I'm not sure how should i approach the release option since I don't think I can check if a fish is rare or not without overcomplicating a lot of things. An option to release all fish except the ones you manually add in a WhiteList would be enough?

**Comment by WilliamW1979** [comment]
That would be perfect.
