### ISSUE TITLE
Auto accept of collectibles

### ISSUE THREAD

**Issue by WilliamW1979** [InitialDet/AutoHook#50]
When collectibles are caught, it brings up a popped that asked if you want to keep the collectible or not. Is there a way to have asetting that will auto say yes if enabled.

I did learn that pressing the num0 key twice when it appears will accept it so maybe that will help.

Also thank you for that update with the toggle ... it has really been a big help!

**Comment by InitialDet** [comment]
You can use [YesAlready](https://github.com/daemitus/YesAlready) for it

**Comment by WilliamW1979** [comment]
I experimented with YesAlready and it does the job very well. I didn't even know it existed so thank you for that.
