### ISSUE TITLE
[suggestion] I want a preset for Big Fish

### ISSUE THREAD

**Issue by chinman37** [InitialDet/AutoHook#51]
I'm sorry, my English is not good
I would like to have a function that allows me to select a preset fishing method for big fish.

**Comment by InitialDet** [comment]
Its a planned feature, I just don't have a release date for it yet.

**Comment by chinman37** [comment]
I want the system to support Japanese
Thank you.
I can't wait.

**Comment by InitialDet** [comment]
Sorry for the delay, ive added this in the new version.
