### ISSUE TITLE
[Suggestion] About "StopAfterCaughtLimit"

### ISSUE THREAD

**Issue by DeepseaXX** [InitialDet/AutoHook#52]
Thanks for your great plugin.
I noticed that it can stop after N times of catching, but I wonder if it can be set by "Quantity of fish in inventory "or "after n fishes to be caught", since I might use "double hook" or "triple hook", that the quantities and times don't match. 
"Quantity of fish in inventory " will be useful for "Skysteel fishing rod", and "after n fishes to be caught" will be useful for "Fisher's Intuition".
It would be helpful.

**Comment by InitialDet** [comment]
This might be a complicated request, currently i just check if X fish got gauch Y amount of times during one fishing session, and keeping track of each fish in the inventory, and while possible, will require a lot of changes and to be honest ive been quite busy to make big changes in the plugin. 

That being said i'll keep this in mind when i start being more active with the development again.
