### ISSUE TITLE
[suggestion] Randomized wait times 

### ISSUE THREAD

**Issue by Theletha** [InitialDet/AutoHook#53]
Would be great if there was a delay that could be added between the catch and throw. 
So it could look more human like.

**Comment by InitialDet** [comment]
It already has randomized delays, every action has a different timing. Now if the question is about it still being "too fast", i might add a slider in a future update so the user can select the amount of seconds between each action, but I just dont think a 1/2 second extra delay would make it look more human like if ur just afking either way.

**Comment by Theletha** [comment]
I'm not sure how long u can wait when the bait is caught and u have to pull it out, maybe the slider can be between the max amount of time you can wait and lowest being instant hook.
