### ISSUE TITLE
Config window opens when anyone writes "ah" in chat

### ISSUE THREAD

**Issue by erdelf** [InitialDet/AutoHook#54]
As title says, anyone writing the word `ah` in chat in any channel seems to cause the auto hook config window to open.

Now.. it doesn't happen every time and I haven't figured out what exactly it is listening to, 
but I had conversations where it popped up 5 times.. rather annoying.

**Comment by InitialDet** [comment]
I checked the code and did some testing and this shouldnt happen. All i can think is that you probably have another plugin doing something weird in the background, because my plugin is not listening to chat messeges outside of slash commands like every other plugin.

**Comment by erdelf** [comment]
hm, it's the only plugin doing that for me, but well. Must be something in my local client, then. 
Thank you for checking.
