### ISSUE TITLE
[Suggestion] Spearfishing keeps missing on higher ping

### ISSUE THREAD

**Issue by NoraDR** [InitialDet/AutoHook#56]
Please add some kind of slider to the config menu to adjust how early it fires the gig, I tried it on a fast fish, it gets them in the bottom 2 layers, the 3rd one it misses sometimes and the top layer it misses every single time

**Comment by InitialDet** [comment]
I'll try to improve this, its a very experimental feature and kinda hard to balance the timing wi the way i did

**Comment by InitialDet** [comment]
You can now customize when the gig is activated by selecting a new hitbox size, this could help mitigate the latancy problem by adjusting it.
