### ISSUE TITLE
auto patience forfeits mooch opportunities

### ISSUE THREAD

**Issue by LastExceed** [InitialDet/AutoHook#57]
situation: both `auto patience` and `auto mooch` are enabled, and the patience buff runs out the moment a mooch opportunity arises

desired behaviour: mooch should be used

actual behaviour: patience is cast, forfeiting the mooch opportunity

so far only tested with `global auto patience` + `fish specific auto mooch`, but `global auto mooch` and maybe even `global auto makeshift bait` might be affected as well

**Comment by InitialDet** [comment]
I checked and double checked this but i didnt cancel mooch. 
i'm assuming you didnt have this option enabled in the AutoCast tab?
![image](https://user-images.githubusercontent.com/13919114/212232093-e692026d-2f65-4080-a00f-644cb71ca9d8.png)


Sorry for the delay, i took a break before 6.3
