### ISSUE TITLE
Mooch 2 Check before Prize Catch or P1/2

### ISSUE THREAD

**Issue by resech** [InitialDet/AutoHook#58]
Having an option under Prize Catch in the Auto Casts tab that was something like `Only use when Mooch 2 is unavailable` would be a good way to make sure the 100 GP skill was used before the 200 GP one when going for mooches.

It could be useful on the patience options as well if only a single mooch is required.

**Comment by InitialDet** [comment]
Thanks for the feedback, ive added this in the new version.
