### ISSUE TITLE
Add Collector's glove to Chum to break animation

### ISSUE THREAD

**Issue by litori** [InitialDet/AutoHook#59]
If you cast collector's glove right after chum, it break's the chum animation so you can cast faster.  Just turn off collector's glove afterwards.  It let's you get more casts in.

Video for reference: https://www.youtube.com/watch?v=bX9eOTayZBA

**Comment by InitialDet** [comment]
I've seen a lot of bots doing this and its kinda sus, ill keep this in my for later but not now.
