### ISSUE TITLE
Allow both double hook and triple hook?

### ISSUE THREAD

**Issue by Junie-774** [InitialDet/AutoHook#63]
Hi, I noticed that the "Use double hook (if gp > 400)" and the "Use triple hook (if gp > 700)" options are mutually exclusive in the plugin.
Would it be possible to have them both enabled, with the behavior of triple hook taking priority if gp > 700? I'd like to use double hook if 400 < gp < 700, but if my gp gets above 700, after using a hi-cordial for example, I'd like to use triple hook

**Comment by InitialDet** [comment]
I'm not opposed to do this, but in 99% of the situations triple hook will never be used. And AFAIK using two double hooks (800gp) is more efficient then using a single tripple hook, so i really dont see how that would be a good thing.

**Comment by ramblinguy** [comment]
Isn't triple hooks more efficient? Since with double hook, you get 1 extra fish for 400 GP. With Triple Hook, you get 2 extra fish for 700 GP, or 350 GP per extra fish. (Assuming Jhingas)

**Comment by InitialDet** [comment]
Yeah ur right, Im just a lil stupid. Either way i cant see a real benefit of having both at the same time, you'll basically only see triple hook when starting with max GP, or if you get really lucky with the cordial and go above 700. But i think at this point its best to just use triple hook? specially if ur just afk
