### ISSUE TITLE
[Question] Chum Timer wait settings

### ISSUE THREAD

**Issue by github-1348A55** [InitialDet/AutoHook#65]
In the normal wait settings...
Min. Wait (upper section)
Max. Wait (lower section)
The order of the display is like this.

in the Chum Timer wait settings...
this is reversed, which is confusing.
Max. Wait (upper section)
Min. Wait (lower section)
Is this an intentional configuration on the part of the creator?

**Comment by InitialDet** [comment]
Oh i really didnt notice that, thank you for reporting. I'll fix it

**Comment by github-1348A55** [comment]
Thank you for your reply.
This plugin is one of the fun things to do in XIV.

**Comment by InitialDet** [comment]
Im glad youre enjoying it o/
The new version should be available now.
