### ISSUE TITLE
Feature Request: Automatically Approve of Collectable Caught

### ISSUE THREAD

**Issue by KingsRoar** [InitialDet/AutoHook#71]
Hello!

First of all, thank you so very much for this plug-in. It's made my life as a fisher so much easier and I cannot thank you enough. I have recently tried my hand at fishing for collectables, but I ran into a pause in the automated process, which is that I have to click "yes" when a collectable comes up. I was wondering if it was possible to 1) _have the process of saying "yes" to the collectable automated_ and 2) if it could _approve of the collectable ONLY if it is equal to or above a certain threshold number_ we set as well! Those additions would be so, so wonderful! Thank you for your time and effort with this plug-in!! <3

**Comment by Jaksuhn** [comment]
https://github.com/InitialDet/AutoHook/blob/main/AcceptCollectable.md

**Comment by KingsRoar** [comment]
Oh my gosh! Thank you so much!!
