### ISSUE TITLE
Option under the [Hook Legendary] checkbox to use either Precision or Powerful Hookset

### ISSUE THREAD

**Issue by cc12138030** [InitialDet/AutoHook#8]
Drop down option under the [Hook Legendary] checkbox to use either Precision or Powerful Hookset

Not sure which hookset this option does by default. I assume powerful, but several legendary bites use the precision hookset.

**Comment by InitialDet** [comment]
Could you link me some examples? Most if not all the !!! i checked always used powerful.

**Comment by cc12138030** [comment]
There are a significant number of them. Just with a cursory glance I would say at least 20% of the ' !!! ' tugs are for precision hookset. Here are a few.

https://ffxivteamcraft.com/db/en/item/7902/Cupfish
https://ffxivteamcraft.com/db/en/item/7681/Caterwauler
https://ffxivteamcraft.com/db/en/item/7933/Charon's-Lantern
https://ffxivteamcraft.com/db/en/item/7682/Crystal-Perch
https://ffxivteamcraft.com/db/en/item/28929/Black-Jet
https://ffxivteamcraft.com/db/en/item/16751/Hraesvelgr's-Tear
https://ffxivteamcraft.com/db/en/item/17589/Opabinia
https://ffxivteamcraft.com/db/en/item/15634/The-Soul-of-the-Martyr
https://ffxivteamcraft.com/db/en/item/24213/Princess-Killifish
https://ffxivteamcraft.com/db/en/item/33318/Steel-Razor
https://ffxivteamcraft.com/db/en/item/16753/Hundred-eyed-Axolotl
https://ffxivteamcraft.com/db/en/item/24995/The-Unconditional
https://ffxivteamcraft.com/db/en/item/33242/Ealad-Skaan
https://ffxivteamcraft.com/db/en/item/33241/Cinder-Surprise
https://ffxivteamcraft.com/db/en/item/33316/Aster-Trivi
https://ffxivteamcraft.com/db/en/item/16749/Moggle-Mogpom
https://ffxivteamcraft.com/db/en/item/30438/The-Mother-of-All-Pancakes
https://ffxivteamcraft.com/db/en/item/33322/Celestial
https://ffxivteamcraft.com/db/en/item/33319/Shadeshifter
https://ffxivteamcraft.com/db/en/item/32049/Moonlight-Guppy
https://ffxivteamcraft.com/db/en/item/32052/Sunken-Tome

Can also just go through https://ff14fish.carbuncleplushy.com/ and look at the right hand side how many of the ' !!! ' have the green precision hookset icon.

**Comment by InitialDet** [comment]
Already fair enough, ill see what I can do.

**Comment by cc12138030** [comment]
Hopefully it's not complicated or difficult to implement. I was even thinking there could still just be Powerful as default and then a checkbox for "Precision Hookset Override" since Powerful Hookset is more common. I don't know if that would be easier or however you want to do it. Regardless, it's a very helpful add-on, so thanks for creating it!

**Comment by InitialDet** [comment]
I've added some new options to select your hookset when using Patience, I hope it can be useful/work as intended.
