### ISSUE TITLE
Cast condition : only cast when have X amount GP

### ISSUE THREAD

**Issue by Sparria** [InitialDet/AutoHook#83]
Would be great if able to have the option to Cast only after checking the amount of GP players have, once a player has enough GP trigger the Cast again
This allows minimizing the bait use with every failed Cast if we want to target a particular fish and with every cast able to do DH/TH

**Comment by Nomanaoy** [comment]
agree

**Comment by sheiun** [comment]
Yes sometimes we also use Identical Cast + DH/TH combo but the it'll cast even we don't have enough GP.

**Comment by InitialDet** [comment]
Added on 3.0.0.0
