### ISSUE TITLE
Suggestion: Hook with the "Hook" action

### ISSUE THREAD

**Issue by joshboston723** [InitialDet/AutoHook#84]
I'm scrip farming and I want to use Hook on Weak (!) bites even when Patience is up, so I can mooch the fish into the scrip fish but not spend GP on this fish.

**Comment by retep998** [comment]
A failed hook is slightly faster than not reeling in, so this rather useful.

**Comment by Ad1con** [comment]
This would be great! Even if I am in Patience, I don't necessarily want to Powerful or Precision, sometimes I want to regular Hook despite the Patience debuff.
