### ISSUE TITLE
Mooch loop

### ISSUE THREAD

**Issue by Nanar13** [InitialDet/AutoHook#88]
After catching the last fish with patience up but patience's timer = 0 , the next action is patience whereas you could mooch the last big fish

It breaks mooch loop too early

Spell priority doesn't seem ok : mooch > mooch II > patience (even when buff has disappeared)

Tks for help

**Comment by InitialDet** [comment]
You need to enable the "Don't Cancel Mooch" option, or else you'll lose mooch with auto cast
