### ISSUE TITLE
"AH" in chat from other players bug

### ISSUE THREAD

**Issue by vTemplar** [InitialDet/AutoHook#95]
I've noticed that when even other players say the word "ah" in chat, party chat, alliance chat, it causes the plugin interface to pull up for autohook. So if your in an instance and someone says "ah that makes sense" or something the plugin pops up. Kind of a funny bug but thought I would bring it up because I don't see that it has been mentioned.

**Comment by DevThew** [comment]
Tested with 2 other persons, could not reproduce, tested with party chat on different instances, and on same instance.

**Comment by InitialDet** [comment]
Its probably a conflict with another plugin, but the /ah command was removed because its not the first time it happens
