### ISSUE TITLE
[Suggestion] "Auto Cast" options for Custom Presets

### ISSUE THREAD

**Issue by Mr-Ouija** [InitialDet/AutoHook#97]
Place global features from "Auto Casts" tab under "Custom Presets" to enable different setups based on preset.

Depending on the fish, I use different setups in the auto-cast tab: whether or not to use Patience, Prize Catch, Chum, _Collector's Glove_ -- which would also be an amazing addition with this. Problem is, I always have a hard time remembering what to use, and have to look-up and re-configure the auto-cast tab on a fish-by-fish basis. If possible, it'd be nice to have these options saved under a Custom Preset, instead of enabled globally.

**Comment by InitialDet** [comment]
Added on 3.0.0.0
